# Generated by Django 5.0.3 on 2024-04-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0024_alter_claudetranslator_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azureaitranslator',
            name='deloyment_name',
        ),
        migrations.RemoveField(
            model_name='azureaitranslator',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='azureaitranslator',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='claudetranslator',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='geminitranslator',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='moonshotaitranslator',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='openaitranslator',
            name='prompt',
        ),
        migrations.AddField(
            model_name='azureaitranslator',
            name='base_url',
            field=models.URLField(default='https://api.openai.com/v1', verbose_name='API URL'),
        ),
        migrations.AddField(
            model_name='azureaitranslator',
            name='model',
            field=models.CharField(default='Your Deployment Name', max_length=100, verbose_name='Deloyment Name'),
        ),
        migrations.AddField(
            model_name='azureaitranslator',
            name='translate_prompt',
            field=models.TextField(default='Translate only the text into {target_language},only returns translations.'),
        ),
        migrations.AddField(
            model_name='claudetranslator',
            name='translate_prompt',
            field=models.TextField(default='Translate only the text into {target_language},only returns translations.'),
        ),
        migrations.AddField(
            model_name='geminitranslator',
            name='translate_prompt',
            field=models.TextField(default='Translate only the text from the following into {target_language},only returns translations.'),
        ),
        migrations.AddField(
            model_name='moonshotaitranslator',
            name='translate_prompt',
            field=models.TextField(default='Translate only the text into {target_language},only returns translations.'),
        ),
        migrations.AddField(
            model_name='openaitranslator',
            name='translate_prompt',
            field=models.TextField(default='Translate only the text into {target_language},only returns translations.'),
        ),
        migrations.AlterField(
            model_name='azureaitranslator',
            name='api_key',
            field=models.URLField(default='https://example.openai.azure.com/', verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='azureaitranslator',
            name='summary_prompt',
            field=models.TextField(default='Summarize the following text in {target_language}.'),
        ),
        migrations.AlterField(
            model_name='claudetranslator',
            name='summary_prompt',
            field=models.TextField(default='Summarize the following text in {target_language}.'),
        ),
        migrations.AlterField(
            model_name='geminitranslator',
            name='summary_prompt',
            field=models.TextField(default='Summarize the following text in {target_language}.'),
        ),
        migrations.AlterField(
            model_name='moonshotaitranslator',
            name='summary_prompt',
            field=models.TextField(default='Summarize the following text in {target_language}.'),
        ),
        migrations.AlterField(
            model_name='openaitranslator',
            name='summary_prompt',
            field=models.TextField(default='Summarize the following text in {target_language}.'),
        ),
    ]
